Create table "DadosCadastrais" (
	"razao" Varchar2 (60),
	"nomefan" Varchar2 (60),
	"cnpj" Varchar2 (14),
	"inscEst" Varchar2 (9),
	"dataFun" Date,
	"ramoAtiv" Varchar2 (30),
	"endereco" Varchar2 (80),
	"bairro" Varchar2 (60),
	"cep" Varchar2 (8),
	"cidade" Varchar2 (60),
	"uf" Char (2),
	"fone" Varchar2 (9),
	"email" Varchar2 (60),
	"socio1" Varchar2 (60),
	"socio2" Varchar2 (60),
	"socio3" Varchar2 (60),
	"cargo1" Varchar2 (60),
	"cargo2" Varchar2 (60),
	"cargo3" Varchar2 (60)); 


Create table "MarketingComunicacao" (
	"prodMVen1" Varchar2 (60),
	"prodMVen2" Varchar2 (60),
	"prodMVen3" Varchar2 (60),
	"qtdM1" Integer,
	"qtdM2" Integer,
	"qtdM3" Integer,
	"undMed1" Varchar2 (10),
	"undMed2" Varchar2 (10),
	"undMed3" Varchar2 (10),
	"margeLuc1" Integer,
	"margeLuc2" Integer,
	"margeLuc3" Integer,
	"fatura1" Integer,
	"fatura2" Integer,
	"fatura3" Integer,
	"concorrente1" Varchar2 (30),
	"concorrente2" Varchar2 (30),
	"concorrent3" Varchar2 (30),
	"visitConcoS" Char (3),
	"visitConcoN" Char (3),
	"pontoAten" Varchar2 (11),
	"pontoEstac" Varchar2 (14),
	"pontoPreco" Varchar2 (5),
	"pontoVarie" Varchar2 (9),
	"pontoEspFisico" Varchar2 (13),
	"pontoLocal" Varchar2 (11),
	"pontoQuali" Varchar2 (9),
	"pontoOutros" Varchar2 (60),
	"pontoMAten" Varchar2 (11),
	"pontoMEstac" Varchar2 (14),
	"pontoMPreco" Varchar2 (5),
	"pontoMVarie" Varchar2 (9),
	"pontoMEspFisico" Varchar2 (13),
	"pontoMLocal" Varchar2 (11),
	"pontoMQuali" Varchar2 (9),
	"pontoMOutros" Varchar2 (60),
	"promo1" Varchar2 (25),
	"promo2" Varchar2 (15),
	"promo3" Varchar2 (15),
	"meio1" Varchar2 (5),
	"meio2" Varchar2 (8),
	"meio3" Varchar2 (8),
	"meio4" Varchar2 (60),
	"estSinalS" Char (3),
	"estSinalN" Char (3),
	"espPromoS" Char (3),
	"espPromoN" Char (3));

Create table "Precos" (
	"formPreco1" Varchar2 (26),
	"formPreco2" Varchar2 (25),
	"formPreco3" Varchar2 (40),
	"precoConc1" Varchar2 (5),
	"precoConc2" Varchar2 (6),
	"precoConc3" Varchar2 (6)); 


Create table "Vendas" (
	"mesAno1" Date,
	"mesAno2" Date,
	"mesAno3" Date,
	"mesAno4" Date,
	"mesAno5" Date,
	"mesAno6" Date,
	"faturamento1" Float,
	"faturamento2" Float,
	"faturamento3" Float,
	"faturamento4" Float,
	"faturamento5" Float,
	"faturamento6" Float,
	"periodoMes1" Date,
	"periodoMes2" Date,
	"dia1" Char (3),
	"dia2" Char (3),
	"dia3" Char (3),
	"dia4" Char (3),
	"dia5" Char (3),
	"dia6" Char (3),
	"dia7" Char (3),
	"horaMov1" Varchar2 (5),
	"horaMov2" Varchar2 (5),
	"horaMov3" Varchar2 (5),
	"formPag1" Varchar2 (20),
	"formPag2" Varchar2 (20),
	"formPag3" Varchar2 (20),
	"formPag4" Varchar2 (20),
	"formPag5" Varchar2 (20),
	"formPag6" Varchar2 (60),
	"valorMedioP" Float,
	"valorMedioM" Float); 

Create table "Compras" (
	"razaoFant1" Varchar2 (60),
	"razaoFant2" Varchar2 (60),
	"razaoFant3" Varchar2 (60),
	"cidUf1" Varchar2 (60),
	"cidUf2" Varchar2 (60),
	"cidUf3" Varchar2 (60),
	"produto1" Varchar2 (60),
	"produto2" Varchar2 (60),
	"produto3" Varchar2 (60),
	"lotMinimo1" Integer,
	"lotMinimo2" Integer,
	"lotMinimo3" Integer,
	"relacionamento1" Varchar2 (50),
	"relacionamento2" Varchar2 (50),
	"relacionamento3" Varchar2 (50),
	"mesAno1" Date,
	"mesAno2" Date,
	"mesAno3" Date,
	"mesAno4" Date,
	"mesAno5" Date,
	"mesAno6" Date,
	"compra1" Float,
	"compra2" Float,
	"compra3" Float,
	"compra4" Float,
	"compra5" Float,
	"compra6" Float); 

Create table "Clientes" (
	"quantCli" Integer,
	"classeA" Integer,
	"classeB" Integer,
	"classeC" Integer,
	"classeD" Integer,
	"idade1" Integer,
	"idade2" Integer,
	"idade3" Integer,
	"idade4" Integer,
	"masc" Integer,
	"fem" Integer,
	"vendEmpS" Varchar2 (20),
	"vendEmpN" Char (3),
	"pesqCli1" Varchar2 (20),
	"pesqCli2" Varchar2 (15),
	"pesqCli3" Varchar2 (10));

Create table "RecursosHumanos" (
	"qtdColab" Integer,
	"colabT1" Varchar2 (60),
	"colabT2" Char (3),
	"escola1" Varchar2 (20),
	"escola2" Varchar2 (20),
	"escola3" Varchar2 (20),
	"contColab1" Varchar2 (20),
	"contColab2" Varchar2 (20),
	"contColab3" Varchar2 (35),
	"fatPrior1" Varchar2 (20),
	"fatPrior2" Varchar2 (20),
	"fatPrior3" Varchar2 (20),
	"ativMotiv1" Varchar2 (20),
	"ativMotiv2" Varchar2 (20),
	"ativMotiv3" Varchar2 (35),
	"demiCont" Varchar2 (100));

Create table "AdmFinanContabil" (
	"tipoM1" Char (1),
	"tipoM2" Char (1),
	"tipoM3" Char (1),
	"tipoM4" Char (1),
	"tipoM5" Char (1),
	"tipoM6" Char (1),
	"tipoM7" Char (1),
	"tipoM8" Varchar2 (30),
	"tipoI1" Char (1),
	"tipoI2" Char (1),
	"tipoI3" Char (1),
	"tipoI4" Char (1),
	"tipoI5" Char (1),
	"tipoI6" Char (1),
	"tipoI7" Char (1),
	"tipoI8" Varchar2 (30),
	"planeja1" Varchar2 (100),
	"planeja2" Char (3),
	"recursoTer1" Varchar2 (20),
	"recursoTer2" Varchar2 (20),
	"recursoTer3" Varchar2 (20),
	"recursoTer4" Varchar2 (20),
	"recursoTer5" Varchar2 (20),
	"recursoTer6" Varchar2 (20),
	"maiorG1" Varchar2 (20),
	"maiorG2" Varchar2 (20),
	"maiorG3" Varchar2 (20),
	"maiorG4" Varchar2 (20),
	"maiorG5" Varchar2 (20),
	"maiorG6" Varchar2 (20),
	"maiorG7" Varchar2 (20),
	"maiorG8" Varchar2 (80));

Create table "Juridico" (
	"impostoEmpS" Char (3),
	"mpostoEmpN" Char (3),
	"autuacaoFiscS" Char (3),
	"autuacaoFiscN" Char (3),
	"acaoJudicialS" Char (3),
	"acaoJudicialN" Char (3),
	"tratFor1" Varchar2 (20),
	"tratFor2" Varchar2 (20),
	"cobanEmp1" Varchar2 (20),
	"cobanEmp2" Varchar2 (20),
	"cobanEmp3" Varchar2 (20),
	"cobanEmp4" Varchar2 (60),
	"acessJuridicaS" Char (3),
	"acessJuridicaN" Char (3),
	"parcerAcic" Varchar2 (200),
	"parcerUnipar" Varchar2 (200));
